from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from agent_handoff.baseline.runner import load_baseline_result
from agent_handoff.models import BaselineRunResult, LayerResult

LAYER_LABELS = {
    "prompt_drift": "Prompt drift",
    "tool_schema": "Tool call / schema",
    "memory_bleed": "Memory bleed",
    "retrieval": "Retrieval miss",
}

KNOWN_LIMITATIONS = [
    "Replays frozen transcripts only — does not invoke live LLM or tool endpoints.",
    "Retrieval scoring compares fixture lists, not embedding similarity or rerankers.",
    "Memory bleed checks are substring-based heuristics, not full session isolation proofs.",
    "Tool schema validation covers required argument keys, not full JSON Schema semantics.",
    "Pass/fail is deterministic but not a substitute for production load or security review.",
]


def _status_icon(passed: bool) -> str:
    return "PASS" if passed else "FAIL"


def _format_layer_row(layer: LayerResult) -> str:
    status = _status_icon(layer.passed)
    row = f"| {LAYER_LABELS.get(layer.layer, layer.layer)} | {status} | {layer.message} |"
    return row


def _aggregate_layer_stats(result: BaselineRunResult) -> dict[str, dict[str, int]]:
    stats: dict[str, dict[str, int]] = {}
    for scenario in result.scenarios:
        for layer in scenario.layers:
            bucket = stats.setdefault(layer.layer, {"passed": 0, "failed": 0})
            if layer.passed:
                bucket["passed"] += 1
            else:
                bucket["failed"] += 1
    return stats


def generate_report(
    result: BaselineRunResult,
    *,
    client_name: str = "Client",
    project_name: str | None = None,
) -> str:
    counts = result.summary_counts()
    project = project_name or result.config_name
    generated_at = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")
    overall = "Approved for handoff" if result.passed else "Blocked — regressions detected"

    lines: list[str] = [
        f"# Agent Handoff Sign-Off Report — {client_name}",
        "",
        f"**Project:** {project}  ",
        f"**Generated:** {generated_at}  ",
        f"**Baseline config:** `{result.config_path}`  ",
        f"**Overall status:** {overall}",
        "",
        "## Executive summary",
        "",
    ]

    if result.passed:
        lines.extend(
            [
                f"All {counts['total']} frozen scenarios passed across the four "
                "regression layers. No prompt drift, tool/schema mismatch, memory "
                "bleed, or retrieval miss was detected against the frozen baseline.",
            ]
        )
    else:
        lines.extend(
            [
                f"{counts['failed']} of {counts['total']} scenarios failed one or "
                "more regression layers. Review per-scenario details before sign-off.",
            ]
        )

    lines.extend(["", "## Per-layer results", ""])
    layer_stats = _aggregate_layer_stats(result)
    if layer_stats:
        lines.extend(
            [
                "| Layer | Passed | Failed |",
                "| --- | ---: | ---: |",
            ]
        )
        for layer_key in ("prompt_drift", "tool_schema", "memory_bleed", "retrieval"):
            if layer_key not in layer_stats:
                continue
            bucket = layer_stats[layer_key]
            label = LAYER_LABELS[layer_key]
            lines.append(
                f"| {label} | {bucket['passed']} | {bucket['failed']} |"
            )
    else:
        lines.append("_No layer checks were configured._")

    lines.extend(["", "## Scenario detail", ""])
    for scenario in result.scenarios:
        status = _status_icon(scenario.passed)
        lines.extend(
            [
                f"### {scenario.scenario_name} (`{scenario.scenario_id}`) — {status}",
                "",
                "| Layer | Status | Summary |",
                "| --- | --- | --- |",
            ]
        )
        if scenario.layers:
            for layer in scenario.layers:
                lines.append(_format_layer_row(layer))
        else:
            lines.append("| _none_ | PASS | no checks configured |")

        failure_details = [
            detail
            for layer in scenario.layers
            if not layer.passed
            for detail in layer.details
        ]
        if failure_details:
            lines.extend(["", "**Failure details:**", ""])
            for detail in failure_details:
                lines.append(f"- {detail}")
        lines.append("")

    lines.extend(["## Known limitations", ""])
    for item in KNOWN_LIMITATIONS:
        lines.append(f"- {item}")
    lines.append("")

    lines.extend(
        [
            "---",
            "",
            "_Generated by [Agent Handoff Kit](https://github.com/mastroke/agent-handoff-kit). "
            "This report reflects deterministic replay against frozen fixtures, not live production traffic._",
            "",
        ]
    )
    return "\n".join(lines)


def generate_report_from_file(
    results_path: Path,
    output_path: Path,
    *,
    client_name: str = "Client",
    project_name: str | None = None,
) -> str:
    result = load_baseline_result(results_path)
    markdown = generate_report(
        result,
        client_name=client_name,
        project_name=project_name,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    return markdown
