"""Markdown acceptance report generation."""

from __future__ import annotations

from typing import Any


def render_markdown_report(data: dict[str, Any]) -> str:
    verdict = data["verdict"]
    lines = [
        f"# {data.get('title', 'Agent Acceptance Report')}",
        "",
        "Cross-layer baseline: **Layer A** = full agent endpoint, "
        "**Layer B** = raw pinned API, same frozen probe set.",
        "",
        f"- Frozen probe version: `{data.get('frozen_probe_version', 'unknown')}`",
        f"- Run started: {data.get('started_at', 'n/a')}",
        f"- Run finished: {data.get('finished_at', 'n/a')}",
        "",
        "## Overall verdict",
        "",
        f"**Classification:** `{verdict['classification']}`",
        "",
        verdict["summary"],
        "",
        "| Metric | Layer A (agent) | Layer B (raw API) |",
        "| --- | ---: | ---: |",
        f"| Pass rate | {verdict['pass_rate_a']:.0%} | {verdict['pass_rate_b']:.0%} |",
        f"| Baseline met | {verdict['baseline_met_count']} | — |",
        f"| Agent value-add | {verdict['agent_value_add_count']} | — |",
        f"| Agent regression | {verdict['agent_regression_count']} | — |",
        f"| Shared failure | {verdict['shared_failure_count']} | — |",
        f"| Total probes | {verdict['total_probes']} | {verdict['total_probes']} |",
        "",
    ]

    for suite in data.get("suites", []):
        sv = suite["verdict"]
        lines.extend(
            [
                f"## Suite: {suite['name']} (v{suite['version']})",
                "",
                suite.get("description", ""),
                "",
                f"**Suite verdict:** `{sv['classification']}` — {sv['summary']}",
                "",
                "| Probe | Layer A | Layer B | Attribution |",
                "| --- | --- | --- | --- |",
            ]
        )
        for probe in suite.get("probes", []):
            lines.append(
                "| {probe_id} | {a} | {b} | `{attr}` |".format(
                    probe_id=probe["probe_id"],
                    a=probe["layer_a"]["outcome"],
                    b=probe["layer_b"]["outcome"],
                    attr=probe["attribution"]["classification"],
                )
            )
        lines.append("")

    lines.extend(
        [
            "## Methodology note",
            "",
            "This report applies the cross-layer baseline from the "
            "[agent-loop-hillclimber](https://github.com/mastroke/agent-loop-hillclimber) "
            "methodology: a frozen probe harness runs identically against the full agent "
            "endpoint and a pinned raw API so failures can be attributed to orchestration "
            "rather than model drift.",
            "",
            "_Generated by [agent-acceptance-kit](https://github.com/mastroke/agent-acceptance-kit)._",
            "",
        ]
    )
    return "\n".join(lines)
